### ISSUE TITLE
Problem loading scripts/libraries

### ISSUE THREAD

**Issue by ldash** [repocad/lib#1]
Great idea with online, free, simple 2D CAD scripting!

I've been working on a drawing (HousePlan), hit SAVE, it said that it saved it to GitHub (it worked for me before), then I closed the editor window, went to check if the changes were actually there on GitHub and they weren't, opened the editor back up and the code textarea is blank... Moreover, if I try to import a script (geometry2d in my case), there's a red error message: Script geometry2d failed to load with error: Response(0,0,)

**Comment by oleegholm** [comment]
Hi Lev,
Thanks for your comment. I can see you are right, there is a major issue with script loading and script import. Also the library page is empty. I looked your script up and it exists in the github repo at
https://github.com/repocad/lib/blob/master/HousePlan
So the problem is not with github but lies in the editor. We will look into it asap!
cheers, Ole

**Comment by oleegholm** [comment]
NB: console reads: Failed to parse SourceMap: http://repocad.com/core-opt.js.map

**Comment by ldash** [comment]
Thanks, Ole, for your prompt reply. Yes, a copy of my script exists and it's a version from last night.
Looks like some substantial changes I was working on this morning are lost, though.

Once again, the code initially loaded fine, was working fine, and the SAVE operation was confirmed by the message as successful. If only there was an error message, I would've not closed the editor window in a haste and copied the code elsewhere...
So this part definitely needs to be fixed, better error handling, messaging, alerts.
That's besides the actual broken part of libraries not loading.

I understand that the product is a work in progress, so it was foolish for me to rely on it solely, I will verify the save operation from now on, before closing the editor.

**Comment by Jegp** [comment]
Hi @ldash! I'm sorry to hear about your lost work. It certainly is a work in progress, but we try to keep it as stable as possible. Your issues were due to an unexpected reboot of the server by our provider, so scripts failed to load and changes was lost on the way to GitHub. It's fixed now, so you can get back to it.
Impressive work you've done by the way and I'm glad to see you find it useful! You can see we're still quite young, so please keep the feedback coming :-)

**Comment by ldash** [comment]
Thanks @Jegp 

I'm still having some issues with loading the predefined libraries, though, not as severe.

Before the initial issue arose I took the liberty of modifying "geometry2d" just a tad by adding a couple of more convenience functions. (May be, it being a "core" library, that shouldn't be allowed really and I should define these extra convenience methods locally within my own script, though, I think, the community would fine them useful.)

These changes used to be pulled in just fine before the problem occured, but now it seems that the editor is always pulling in the unedited original version of "geometry2d". I'm not sure, where it's getting it from as the version on github is the edited version.

Thanks.

**Comment by Jegp** [comment]
Hi @ldash. We envisioned every script out there as open and accessible for all, so it's meant to be changed and tampered with :-) Keep up the great work.
There might be some browser caching involved, because the version being loaded should - as you say - be up to date. Could you perhaps try to remove the cache and see if that helps. In the meantime I'll make an issue to see if we can invalidate old script files (issue opened here: https://github.com/repocad/server/issues/2)

**Comment by ldash** [comment]
Thanks @Jegp It seems to be working fine for me now and it probably was the browser caching issue (though, I think, I tried in Chrome opening the console and doing a "hard reset", but that didn't help at the time). But then I really don't remember now, which computer I had the issue on the office or the home one... At any rate, you suggestion of invalidating old scripts sounds great! Meanwhile, I'll open another issue I came across ;)
